### ISSUE TITLE
Example script/data error

### ISSUE THREAD

**Issue by pkells12** [AllenInstitute/deepinterpolation#5]
Hi Jerome,

Been looking forward to this package since COSYNE! I've installed the package successfully. However, when I attempt to run the provided example code I run into the following error:

2020-11-02 16:53:08.495032: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-11-02 16:53:08.495091: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-11-02 16:53:34.622746: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-11-02 16:53:34.622820: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-11-02 16:53:34.622865: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (cn0908): /proc/driver/nvidia/version does not exist
2020-11-02 16:53:34.623393: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-02 16:53:34.670172: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300000000 Hz
2020-11-02 16:53:34.672065: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555901dd10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-02 16:53:34.672099: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/5
WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.
10/10 [==============================] - 8s 766ms/step - loss: 0.4563 - val_loss: 0.3940
Epoch 2/5
WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.
10/10 [==============================] - 8s 775ms/step - loss: 0.3824 - val_loss: 0.3853
Epoch 3/5
WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.
10/10 [==============================] - 8s 775ms/step - loss: 0.3707 - val_loss: 0.3788
Epoch 4/5
WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.
10/10 [==============================] - 7s 749ms/step - loss: 0.3861 - val_loss: 0.3744
Epoch 5/5
WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.
10/10 [==============================] - 8s 761ms/step - loss: 0.3881 - val_loss: 0.3708
Traceback (most recent call last):
  File "example_tiny_ephys_training.py", line 151, in <module>
    training_class.finalize()
  File "/home/kellspa/.local/lib/python3.8/site-packages/deepinterpolation-0.1.0-py3.8.egg/deepinterpolation/trainor_collection.py", line 231, in finalize
  File "/data/kellspa/conda/envs/deepinterp/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1978, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "/data/kellspa/conda/envs/deepinterp/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 130, in save_model
    hdf5_format.save_model_to_hdf5(
  File "/data/kellspa/conda/envs/deepinterp/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 119, in save_model_to_hdf5
    save_weights_to_hdf5_group(model_weights_group, model_layers)
  File "/data/kellspa/conda/envs/deepinterp/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 640, in save_weights_to_hdf5_group
    param_dset = g.create_dataset(name, val.shape, dtype=val.dtype)
  File "/data/kellspa/conda/envs/deepinterp/lib/python3.8/site-packages/h5py/_hl/group.py", line 143, in create_dataset
    if '/' in name:
TypeError: a bytes-like object is required, not 'str'

I've changed my jobdir variable from "/Users/jeromel/test" to a test folder I previously created. Any idea what may be going on here?

Thanks and I look forward to running this on some of my 2P calcium movies :D

**Comment by jeromelecoq** [comment]
Nice to hear you were looking forward to this. I was also looking forward to sharing it with the community. I hope it is going to be helpful to all of us suffering from shot noise for so long. We eventually managed to shot that beast :-)

Looks like an error related to creating the output h5 file. Did you modify the output path as well?

**Comment by jeromelecoq** [comment]
Maybe you need to convert the string to a recursive string? 

r"blabla"
instead of 
"blabla"

**Comment by jeromelecoq** [comment]
Also, looking at your stack, you are running this on a machine without CUDA or GPU support. I designed the demo to work on all machine but consider working on that at some point.

**Comment by pkells12** [comment]
Thanks for the quick response! I was able to get the example scripts running well on my machine. For some reason the h5py package wasn't installed properly. I installed it and everything ran fine. 

In regards to the GPU comment, for some reason I'm unable to get it working with the GPUs on my local cluster.. Whenever I allocate GPU resources I get the same 'could not load dynamic library'... errors near the beginning. I can copy/paste the error here if you'd like to troubleshoot the error but I'm going to discuss it with our support staff here at the NIH which may be much easier. I'll let you know if we can't get it going with the GPUs. Seriously excited to get it going...

Thanks again, Jerome!

**Comment by jeromelecoq** [comment]
This page has been helpful to me : https://www.tensorflow.org/install/source#linux

It tells you which CUDA version you want installed along with TensorFlow version number. On our cluster, CUDA is installed by our IT department so I had to match what was on the cluster. 

This could be the problem.

**Comment by pkells12** [comment]
My IT department was able to help me with the GPU issue. I was having issues loading the proper CUDA/cuDNN modules on our cluster. 

I'm going to attempt to train the network on some of my 2PI data hopefully over the weekend using some motion corrected tiffs. I've found some of the parameters in the paper for training on 2PI data so I'll try editing the example training script to get it going. I'm assuming I need to change the generator_test_param and generator_param to SingleTifGenerator? I'll also need to work with the CollectorGenerator since I'm training on multiple tif files, correct?

If I missed any important steps or if you have any tips/suggestions I'm all ears.

Thanks!

**Comment by jeromelecoq** [comment]
Right. If you are using tiff files, the tiff generator should work. The collector is used to train from a list of files. I used this for ephys training. The collector will randomize batches so that data from each file will be randomly used throughout training. 

This file should be helpful for 2p data : https://github.com/AllenInstitute/deepinterpolation/blob/master/examples/paper_generation_code/multi_ophys/multi-padding/2020-06-15-local_ophys_training_pre_30_post_30.py

I used a different generator for 2p data because I was pulling data from h5 files with a pre-packaged json files to keep track of which exact frames were used. The json generator is directly doing the multi-file training so I was not using the collector. 

Here is an example json files https://github.com/AllenInstitute/deepinterpolation/blob/master/examples/paper_generation_code/json_data/2020-06-16-val-semi-large-single-plane-Ai93-norm.json

My json files were huge because I was pulling from thousands movies. Here is the data used to train the big 2p networks
https://github.com/AllenInstitute/deepinterpolation/blob/master/examples/paper_generation_code/json_data/2019-09-05-train-very-large-single-plane-Ai93-norm.json

Make sure to follow the training using a separate validation set. You want the validation frames not be too close to the training frames to avoid some leakage in between.

**Comment by pkells12** [comment]
Great, those resources make things a bit more clear. I must admit I'm not an expert in either python or deep learning so some aspects of the code are still a bit hazy.. I have made a decent amount of progress getting things set up and processing some movies though. 

I attempted to run one of my tif movies through your pretrained models (both Ai93 and Ai148). The denoising looks like it worked extremely well but I have an issue with flickering. I assumed this was because we have different recording parameters - I image at 45 Hz and am using a different calcium indicator, jRGECO1a (somewhat similar kinetics to gcamp6f though).
<img width="1016" alt="Ai93_6841_012520_frames_50001_51000" src="https://user-images.githubusercontent.com/59375740/98486367-ef8d2280-21ea-11eb-9d45-a0d444ef37e8.png">


I also trained a few networks (both unet_single_1024 and padded_unet_single_1024) on a small dataset with different validation data sets (same animal different recording day or different animal). The denoising seems to have worked quite well considering the small amount of data (~3000 frames). 
<img width="1023" alt="6841_012520_frames_4000_4999" src="https://user-images.githubusercontent.com/59375740/98486529-bc975e80-21eb-11eb-9c79-4234b27f9f64.png">


However, I still have the flickering issue in the final output. I've run the results through suite2p and as expected the fluorescence traces are quite jerky and for some reason the mean image (enhanced mean image) is just black (gray):
![results](https://user-images.githubusercontent.com/59375740/98486843-b6a27d00-21ed-11eb-8fbc-bba9c9b965a9.png)


Any idea on what might be the cause?

Here are the parameters I'm using in the inference file:

generator_param["type"] = "generator"
generator_param["name"] = "SingleTifGenerator"
generator_param["pre_post_frame"] = 45
generator_param["pre_post_omission"] = 0
generator_param["steps_per_epoch"] = 10

generator_param["train_path"] = os.path.join(
    pathlib.Path(__file__).parent.absolute(),
    "/data/kellspa",
    "test_deepinterp/train_data",
    "6841_012520_frames_1_5000_raw.tif",
)

generator_param["batch_size"] = 2
generator_param["start_frame"] = 4000
generator_param["end_frame"] = -1  # -1 to go until the end.
generator_param[
    "randomize"
] = 0  # This is important to keep the order and avoid the randomization used during training

inferrence_param["type"] = "inferrence"
inferrence_param["name"] = "core_inferrence"

inferrence_param[
    "model_path"
] = "/data/kellspa/test_deepinterp/models/unet_single_1024_mean_absolute_error_2020_11_08_15_00/2020_11_08_15_00_unet_single_1024_mean_absolute_error_model.h5"


Thanks again for all the help, Jerome!

**Comment by jeromelecoq** [comment]
Thanks for sharing your progress. I am glad you got this far :-)

I am not sure what is the cause of the flickering. I have not seen this before. Let's try to debug it. 

1/ I am not surprise already after 3000 frames that the output is improved. The biggest improvements in loss are early in training. You should see increasing contrast, reduced motion artifacts, better calcium events as it goes through training with more and more frames. 
2/ The fact that the movies is zero mean after inference is odd. In principle, the inference should add back the mean using the rescale parameters that is default to True
see https://github.com/AllenInstitute/deepinterpolation/blob/master/deepinterpolation/inferrence_collection.py#L181
the Tiff generator is currently using the first 1000 frames to Z-score the data, is it possible that those 1000 frames are different than the rest of the movie in your data? 
3/ I would advise to set "save_raw" to True
https://github.com/AllenInstitute/deepinterpolation/blob/master/deepinterpolation/inferrence_collection.py#L128
to output both denoised and raw frames in your hf5 file for debugging purposes. Perhaps do inference on a small set of frames first. 
4/ Sometimes denoising can reveal issues in the raw data itself. comparing the raw and denoised data side by side is usually helpful. In some cases, I have discovered fine details of the raw data (including artifacts coming from the instrument) that were completely hidden in shot noise before. 
5/ Your suite2p filters looks indeed much more noisy than what I see. I found that Suite2p would output very detailed and clean filters after denoising. This is probably because of that remaining issue. 
6/ If all above fails, feel free to share a 1000 frames h5 file with me to look at the raw and denoised data directly.

**Comment by jeromelecoq** [comment]
Ahah! 

Always let your brain figure things out in the background in diffuse mode. Of course, I figured out the solution 20 min later while doing something else. 

I think I figured out your problem. 

This is a stupid but simple bug to fix
This line: https://github.com/AllenInstitute/deepinterpolation/blob/master/deepinterpolation/generator_collection.py#L698
I did not use tiff files much so I had not use the tif generator this way before. 

The randomization of frames needs to be turn off during inference. 

I will push a code update to the repo to fix that.

**Comment by jeromelecoq** [comment]
If you don't mind, can you close this issue if it actually fixes the problem? I think we need to track each separate issue separately.

**Comment by jeromelecoq** [comment]
@pkells12 
pull the latest code and add the following line to your inference code 
generator_param["randomize"] = 0

That should fix this issue

**Comment by pkells12** [comment]
Unfortunately, that didn't fix the issue :\

I ran a small set of data (90 frames) through the model and it seems that the flickering is not as bad but still present. Also, the raw output seems to have the flickering issue too.. Here's a link to the h5 file: https://www.dropbox.com/s/xcog7i845e912dr/6841_012520_frames_4000_4999.h5?dl=0

I've appended the data that was input for inferrence ('input_data'). Let me know if you want me to upload a larger dataset or anything else.

**Comment by pkells12** [comment]
Just a small update. It does seem that it's randomizing the order of the frames but the generator_param["randomize"]=0 line doesn't seem to fix it as well as a hard coded zero here: https://github.com/AllenInstitute/deepinterpolation/blob/8fa321209ebfbc1865a530cd1d8b9bb6f81c6b84/deepinterpolation/generator_collection.py#L669

Here are example generator and inference json output files:
{"type": "generator", "name": "SingleTifGenerator", "pre_post_frame": 45, "pre_post_omission": 0, "steps_per_epoch": 10, "train_path": "/data/kellspa/test_deepinterp/test_data/6841_012520_frames_50000_52000.tif", "batch_size": 5, "start_frame": 0, "end_frame": 499, "randomize": 0}

{"type": "inferrence", "name": "core_inferrence", "save_raw": true, "model_path": "/data/kellspa/test_deepinterp/models/unet_single_1024_mean_absolute_error_2020_11_08_15_00/2020_11_08_15_00_unet_single_1024_mean_absolute_error_model.h5", "output_file": "/data/kellspa/test_deepinterp/inference/6841_012520_frames_50000_50499.h5"}

**Comment by jeromelecoq** [comment]
I just looked at your h5 file. It seems to me that the data is still randomize. The fact that it is both the raw and processed data would support that. 
Perhaps this could be a code update issue?
Are you sure you re-installed the DeepInterpolation package after pulling? The code would reside in the environment folder.

**Comment by pkells12** [comment]
I thought I did. I've also tried removing and recreating the environment to see if a fresh install would help but I'm still getting the same issue. 

I used 'conda env remove --name deepinterp' then followed the normal install steps. 

Could it be something with the old inference script I'm using? I don't see how that could be the problem if it's pulling from the new build, but I'm sure I'm just making a stupid mistake somewhere..

**Comment by jeromelecoq** [comment]
I am happy to chat more directly. Can you send me your contact info? I feel like you are 99% of the way there. It must be something simple.

**Comment by jeromelecoq** [comment]
Can you try set 
generator_param["batch_size"]  to 1 in your inference code? 

I am wondering if there could be a conflict there.

**Comment by jeromelecoq** [comment]
In principle, the batch size is properly taken care of in the inference code.
https://github.com/AllenInstitute/deepinterpolation/blob/8fa321209ebfbc1865a530cd1d8b9bb6f81c6b84/deepinterpolation/inferrence_collection.py#L199

 I still lean toward a problem with randomization not being turned off somehow

**Comment by pkells12** [comment]
Sad to say that didn't fix it. I'll go ahead and email you to see if we can tease out the issue. Thanks!!

**Comment by jeromelecoq** [comment]
I was able to confirm the flickering was gone with running the model+the same data on my machine+latest repo code. We suspect that something in @pkells12 environment is pointing at the wrong code base.

**Comment by jeromelecoq** [comment]
@pkells12 confirmed the updated code fixed this issue.
